<<<<<<< HEAD
# Generated by Django 4.2 on 2023-04-19 17:02
=======
# Generated by Django 4.2 on 2023-04-22 18:53
>>>>>>> detached

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('publish', 'publish'), ('archive', 'archive')], default='archive', max_length=7)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('directors', models.ManyToManyField(to='movies.director')),
            ],
        ),
    ]
