# Generated by Django 4.2 on 2023-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='biography',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
