# Generated by Django 4.2 on 2023-04-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_director_movie_description_movie_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('archive', 'archive')], default='archive', max_length=7),
        ),
    ]
