# Generated by Django 4.2 on 2023-06-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='publish_in',
            field=models.DateTimeField(null=True),
        ),
    ]
