# Generated by Django 4.2 on 2023-05-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_owner_movie_spectators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovierelation',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Normal'), (3, 'Good'), (4, 'Fine'), (5, 'Incredible')], default=1),
            preserve_default=False,
        ),
    ]
