# Generated by Django 4.2 on 2023-05-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_usermovierelation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
