# Generated by Django 4.2 on 2023-05-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_usermovierelation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovierelation',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
