# Generated by Django 4.2 on 2023-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_usermovierelation_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='biography',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='director',
            constraint=models.UniqueConstraint(fields=('name', 'surname'), name='unique_name_surname'),
        ),
    ]
